#ifndef DANIASSISTANT_GLOBAL_H
#define DANIASSISTANT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DANIASSISTANT_LIBRARY)
#  define DANIASSISTANT_EXPORT Q_DECL_EXPORT
#else
#  define DANIASSISTANT_EXPORT Q_DECL_IMPORT
#endif

#endif // DANIASSISTANT_GLOBAL_H
